_commit: v1.12.1-3-gaade9ad
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: influxdb2
helmRelease: influxdb2
helmRepo: https://helm.influxdata.com/
helmValues: helm/values.yaml
helmVersion: ''
homepageEnabled: false
ingress: false
labels: ''
name: influxdb
namespace: influxdb2
pvc: false
reloader: true
resources:
- external-secrets.yaml
- ingresses.yaml
service: false
serviceAccount: false
upstreamURL: https://www.influxdata.com/products/influxdb/
url: https://github.com/charlesthomas/homelab-influxdb
