---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: influxdb2

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-influxdb

resources:
- resources/namespaces.yaml
<<<<<<< before updating
- resources/ingresses.yaml
=======
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: influxdb
      namespace: influxdb2
      annotations:
        gethomepage.dev/href: https://influxdb.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: influxdb
        gethomepage.dev/name: influxdb
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
>>>>>>> after updating
helmCharts:
- name: influxdb2
  namespace: influxdb2
  releaseName: influxdb2
  repo: https://helm.influxdata.com/
  valuesFile: helm/values.yaml
