---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: influxdb2

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-influxdb

resources:
- resources/external-secrets.yaml
- resources/namespaces.yaml
- resources/ingresses.yaml
helmCharts:
- name: influxdb2
  namespace: influxdb2
  releaseName: influxdb2
  repo: https://helm.influxdata.com/
  valuesFile: helm/values.yaml
