image:
  repository: influxdb
  tag: 2.3.0-alpine
  pullPolicy: IfNotPresent

nameOverride: "influxdb2"
fullnameOverride: ""

startupProbe:
  enabled: false

adminUser:
  organization: "influxdata"
  bucket: "telegraf"
  user: "admin"
  retention_policy: "30d"
  existingSecret: influxdb-auth

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 25Gi
  mountPath: /var/lib/influxdb2
  subPath: ""

initScripts:
  enabled: false
  scripts:
    init.sh: |+
      #!/bin/bash
      influx apply --force yes -u https://raw.githubusercontent.com/influxdata/community-templates/master/influxdb2_operational_monitoring/influxdb2_operational_monitoring.yml

service:
  type: ClusterIP
  port: 8086
  targetPort: 8086
  portName: http

serviceAccount:
  create: true
  name: influxdb2

ingress:
  enabled: false

pdb:
  create: false
